server:
  port: ${SERVER_PORT:8094}

spring:
  application:
    name: rag
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/rag?currentSchema=rag1}
    username: ${DATASOURCE_NAME:rag_user}
    password: ${DATASOURCE_PASSWORD:rag_pass}
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas: rag1
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: codellama:7b
        options:
          temperature: 0.35
          top_p: 0.9
          max_tokens: 2512
          repeat_penalty: 1.1
